name: Build Klipper for AFC-Lite (STM32H723)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout config repo (this repo)
        uses: actions/checkout@v4
        with:
          path: myrepo

      - name: Checkout Klipper sources
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          # ref: v0.12.0  # optional pin

      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      - name: Build firmware (override Makefile target so no double-scan)
        run: |
          set -euxo pipefail
          cd klipper
          cp ../myrepo/.config .config

          # Start clean
          rm -rf out
          mkdir -p out/board-generic

          # *** CRITICAL: Append a new rule that overrides the built-in one ***
          # Last rule wins; this forces out/board -> out/board-generic every time.
          printf '\ncreate-board-link:\n\t@mkdir -p $(BOARD_DIRECTORY)\n\tln -snf $(BOARD_DIRECTORY) out/board\n' >> Makefile

          # Show the rule we just appended (debug)
          tail -n 10 Makefile

          # Build single-threaded with our forced board directory
          make BOARD_DIRECTORY=out/board-generic clean
          make -j1 BOARD_DIRECTORY=out/board-generic

          # Prove where out/board points
          ls -l out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: |
            klipper/out/klipper.bin
            klipper/.config
