name: Build Klipper for AFC-Lite (STM32H723)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Checkout your repo (contains .config)
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          path: myrepo

      # Checkout upstream Klipper source
      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper

      # Install toolchain
      - name: Install ARM toolchain & build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      # Copy config into Klipper and build
      - name: Build firmware
        run: |
          cp myrepo/.config klipper/.config
          cd klipper
          make clean
          make -j1

      # Upload the built firmware
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: |
            klipper/out/klipper.bin
            klipper/.config
