name: klipper-afc-lite-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'myrepo/.config'
      - 'klipper/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Your repo (holds .config)
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          path: myrepo
          fetch-depth: 1

      # Upstream Klipper source
      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ARM toolchain and deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      - name: Build firmware (25MHz and Internal)
        working-directory: klipper
        run: |
          set -euxo pipefail
          cp ../myrepo/.config .config

          # Variant A: 25MHz (as in your .config)
          make clean
          make -j1
          mkdir -p ../artifacts
          cp -v out/klipper.bin ../artifacts/klipper_h723_25mhz.bin
          cp -v .config         ../artifacts/.config_25mhz

          # Variant B: Internal 8MHz (toggle flags)
          sed -i 's/^CONFIG_CLOCK_REF_25MHZ=y/# CONFIG_CLOCK_REF_25MHZ is not set/' .config || true
          grep -q '^CONFIG_CLOCK_REF_INTERNAL=y' .config || printf '\nCONFIG_CLOCK_REF_INTERNAL=y\n' >> .config

          make clean
          make -j1
          cp -v out/klipper.bin ../artifacts/klipper_h723_internal.bin
          cp -v .config         ../artifacts/.config_internal

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-dual
          path: artifacts/*
