name: Build Klipper for AFC-Lite (STM32H723)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Checkout your repo (holds .config)
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          path: myrepo

      # Checkout upstream Klipper sources
      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          # Optional: pin to a tag known-good for you
          # ref: v0.12.0

      # Toolchain
      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      # Build (isolate source path, expose headers, override link rule)
      - name: Build firmware
        run: |
          set -euxo pipefail
          cd klipper
          cp ../myrepo/.config .config

          # Clean slate
          rm -rf out
          mkdir -p out/board-generic

          # Expose sources/headers ONLY via the board dir
          ln -sfn ../src     out/board-generic/src
          ln -sfn ../include out/board-generic/include

          # Force out/board to ALWAYS point at board-generic (not repo root):
          # In `make`, the LAST rule wins — append our override.
          {
            echo '';
            echo 'create-board-link:';
            echo '	@mkdir -p $(BOARD_DIRECTORY)';
            echo '	ln -snf $(BOARD_DIRECTORY) out/board';
          } >> Makefile

          # Debug: show the overridden rule and our links
          tail -n 12 Makefile
          ls -l out
          ls -l out/board-generic

          # Build single-threaded with our forced board directory
          make BOARD_DIRECTORY=out/board-generic clean
          make -j1 BOARD_DIRECTORY=out/board-generic

          # Prove final link target
          ls -l out

      # Upload the built firmware + the exact config used
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: |
            klipper/out/klipper.bin
            klipper/.config
