name: klipper-afc-lite-h723-usb-build
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { repository: Klipper3d/klipper, path: klipper, fetch-depth: 1 }

      - run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3

      - working-directory: klipper
        run: make clean || true

      - working-directory: klipper
        run: printf "%s\n" "CONFIG_LOW_LEVEL_OPTIONS=y" "CONFIG_MACH_STM32=y" "CONFIG_MACH_STM32H7=y" "CONFIG_MACH_STM32H723=y" 'CONFIG_MCU="stm32h723"' "CONFIG_STM32_CLOCK_REF_25M=y" "CONFIG_STM32_FLASH_START_0000=y" "CONFIG_USB=y" "CONFIG_USB_SERIAL=y" "CONFIG_STM32_USB_PA11_PA12=y" > .config

      - working-directory: klipper
        run: make ARCH=arm olddefconfig && grep -E 'MACH_STM32H723|CLOCK_REF_25M|FLASH_START_0000' .config && make ARCH=arm -j1 V=1

      - working-directory: klipper
        run: mkdir -p artifacts && cp out/klipper.bin artifacts/klipper_h723_usb_25mhz_noboot.bin && cp .config artifacts/config_used.txt

      - uses: actions/upload-artifact@v4
        with: { name: klipper-afc-lite-h723-usb, path: klipper/artifacts/* }
