name: Build Klipper for AFC-Lite (STM32H723)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout config repo (this repo)
        uses: actions/checkout@v4
        with:
          path: myrepo

      - name: Checkout Klipper sources
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper

      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      - name: Build firmware (force board dir so no double-scan)
        run: |
          set -euxo pipefail
          cd klipper
          cp ../myrepo/.config .config

          # Ensure the target board directory exists and is empty (no src mirror)
          rm -rf out
          mkdir -p out/board-generic

          # Build single-threaded and FORCE out/board -> out/board-generic
          make BOARD_DIRECTORY=out/board-generic clean
          make -j1 BOARD_DIRECTORY=out/board-generic

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: |
            klipper/out/klipper.bin
            klipper/.config
