      - name: Build (STM32H723 + USB + 25MHz, NO bootloader) — verify toolchain/ELF
        shell: bash
        working-directory: klipper
        run: |
          set -eux

          # Clean (but do NOT distclean)
          make clean || true

          # Write a strict H723 USB + 25MHz + NO bootloader config
          cat > .config <<'EOF'
CONFIG_LOW_LEVEL_OPTIONS=y
CONFIG_MACH_STM32=y
CONFIG_MACH_STM32H7=y
CONFIG_MACH_STM32H723=y
CONFIG_MCU="stm32h723"
CONFIG_STM32_CLOCK_REF_25M=y
# CONFIG_STM32_CLOCK_REF_8M is not set
# CONFIG_STM32_CLOCK_REF_INTERNAL is not set
CONFIG_STM32_FLASH_START_0000=y
# CONFIG_STM32_FLASH_START_20000 is not set
CONFIG_USB=y
CONFIG_USB_SERIAL=y
CONFIG_STM32_USB_PA11_PA12=y
# CONFIG_CANBUS is not set
EOF

          # Resolve defaults on ARM, then sanity-check
          make ARCH=arm olddefconfig

          echo "==== Sanity (Kconfig) ===="
          egrep -n 'CONFIG_MACH_STM32H723|CONFIG_MACH_STM32H7|CONFIG_STM32_CLOCK_REF_|CONFIG_STM32_FLASH_START_|CONFIG_USB(_SERIAL)?|STM32_USB_PA11_PA12' .config || true

          # Hard-fail if anything important flipped
          grep -q '^CONFIG_MACH_STM32H723=y' .config
          grep -q '^CONFIG_STM32_CLOCK_REF_25M=y' .config
          grep -q '^CONFIG_STM32_FLASH_START_0000=y' .config
          grep -q '^CONFIG_USB_SERIAL=y' .config
          grep -q '^CONFIG_STM32_USB_PA11_PA12=y' .config
          ! grep -q '^CONFIG_STM32_CLOCK_REF_8M=y' .config
          ! grep -q '^CONFIG_STM32_FLASH_START_20000=y' .config

          # Build (must show arm-none-eabi-gcc)
          make ARCH=arm -j1 V=1

          # Prove the ELF is ARM and see section sizes
          arm-none-eab
