name: klipper-afc-lite-build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - 'myrepo/.config'
      - 'klipper/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          path: myrepo
          fetch-depth: 1

      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ARM toolchain and deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      # Quick sanity: ensure the config is present and looks like STM32H7
      - name: Show config header
        working-directory: klipper
        run: |
          cp ../myrepo/.config .config
          grep -E 'CONFIG_MACH_|CONFIG_STM32|CONFIG_MCU=|CONFIG_CLOCK_REF_|CONFIG_FLASH_BOOTLOADER|CONFIG_USB_SERIAL|CONFIG_CANBUS' .config || true

      - name: Build firmware (STM32H723 + USB)
        working-directory: klipper
        run: |
          set -euxo pipefail
          # Use your committed .config (already copied above)
          make clean
          make -j1
          mkdir -p ../artifacts
          cp -v out/klipper.bin ../artifacts/klipper_h723_usb_25mhz_noboot.bin
          cp -v .config         ../artifacts/.config_used

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: artifacts/*
