name: Build Klipper AFC-Lite (STM32H723) — dual clock

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'myrepo/.config'
      - 'klipper/**'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Your repo (holds .config)
      - name: Checkout my repo (config)
        uses: actions/checkout@v4
        with:
          path: myrepo
          fetch-depth: 1

      # Upstream Klipper
      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      - name: Sanity reset Klipper tree
        working-directory: klipper
        run: |
          set -euxo pipefail
          git reset --hard
          git clean -xfd

      - name: Debug: scan for duplicate 'identify' declarations
        working-directory: klipper
        run: |
          set -euxo pipefail
          (git grep -n 'DECL_COMMAND("identify"' || true)

      - name: Build firmware (25MHz & Internal)
        working-directory: klipper
        run: |
          set -euxo pipefail
          # Base: your config
          cp ../myrepo/.config .config

          # ---- Variant A: 25 MHz (as in your .config) ----
          make clean
          make -j1
          mkdir -p ../artifacts
          cp -v out/klipper.bin ../artifacts/klipper_h723_25mhz.bin
          cp -v .config         ../artifacts/.config_25mhz

          # ---- Variant B: Internal 8 MHz ----
          if grep -q '^CONFIG_CLOCK_REF_25MHZ=y' .config; then
            sed -i 's/^CONFIG_CLOCK_REF_25MHZ=y/# CONFIG_CLOCK_REF_25MHZ is not set/' .config
          fi
          if ! grep -q '^CONFIG_CLOCK_REF_INTERNAL=y' .config; then
            printf '\nCONFIG_CLOCK_REF_INTERNAL=y\n' >> .config
          fi

          make clean
          make -j1
          cp -v out/klipper.bin ../artifacts/klipper_h723_internal.bin
          cp -v .config         ../artifacts/.config_internal

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-dual
          path: artifacts/*
