name: klipper-afc-lite-h723-usb-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Klipper (upstream)
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ARM toolchain and make
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3

      - name: Create .config (STM32H723 + USB + 25MHz, no bootloader)
        working-directory: klipper
        run: |
          set -euxo pipefail
          cat > .config << 'EOF'
# ==== Klipper MCU Configuration: AFC-Lite (STM32H723) USB, 25MHz, No Bootloader ====
CONFIG_LOW_LEVEL_OPTIONS=y
CONFIG_MACH_STM32=y
CONFIG_STM32H7=y
CONFIG_MCU="stm32h723"
CONFIG_CLOCK_REF_25MHZ=y
# CONFIG_CLOCK_REF_INTERNAL is not set
CONFIG_FLASH_BOOTLOADER=y
CONFIG_FLASH_BOOTLOADER_0K=y
# CONFIG_FLASH_BOOTLOADER_32K is not set
# CONFIG_FLASH_BOOTLOADER_64K is not set
# CONFIG_FLASH_BOOTLOADER_128K is not set
CONFIG_USB_SERIAL=y
# CONFIG_CANBUS is not set
# ==== end ====
EOF
          make olddefconfig
          echo "Key symbols:"
          grep -E 'CONFIG_MACH_|CONFIG_STM32|CONFIG_MCU=|CONFIG_CLOCK_REF_|CONFIG_FLASH_BOOTLOADER|CONFIG_USB_SERIAL|CONFIG_CANBUS' .config || true

      - name: Build firmware (H723 USB)
        working-directory: klipper
        run: |
          set -euxo pipefail
          make clean
          make -j1 V=1
          mkdir -p ../artifacts
          cp -v out/klipper.bin ../artifacts/klipper_h723_usb_25mhz_noboot.bin
          cp -v .config         ../artifacts/.config_used
          echo "---- toolchain check (should show arm-none-eabi-gcc) ----"
          grep -Rsn "arm-none-eabi-gcc" out || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: klipper/artifacts/*
