name: Build Klipper AFC-Lite (STM32H723) — dual clock

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Your repo (holds .config)
      - name: Checkout my repo (config)
        uses: actions/checkout@v4
        with:
          path: myrepo

      # Upstream Klipper
      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          # You can pin a known commit if you want:
          # ref: 96c3ca160e881dbeef8ccbe80f804572b9170d8c

      # Toolchain
      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      # Patch Klipper's buildcommands.py to IGNORE duplicate command names (instead of erroring)
      - name: Patch duplicate-command check (de-dup)
        working-directory: klipper
        run: |
          python3 - << 'PY'
          from pathlib import Path
          p = Path("scripts/buildcommands.py")
          s = p.read_text()
          lines = s.splitlines()
          out = []
          for i,l in enumerate(lines):
            if "Multiple definitions for command" in l:
              # Replace the raise with a warning+continue (robust to spacing)
              indent = l[:len(l)-len(l.lstrip())]
              out.append(indent + 'print("[WARN] duplicate command ignored")')
              out.append(indent + 'continue')
            else:
              out.append(l)
          p.write_text("\n".join(out))
          print("Patched scripts/buildcommands.py to ignore duplicate command definitions.")
          PY

      # Build two variants: 25 MHz crystal AND Internal 8 MHz clock (fallback)
      - name: Build firmware (25MHz & Internal)
        working-directory: klipper
        run: |
          set -euxo pipefail
          # Base: your config
          cp ../myrepo/.config .config

          # ---- Variant A: 25 MHz (as in your .config) ----
          make clean
          make -j1
          mkdir -p ../artifacts
          cp -v out/klipper.bin ../artifacts/klipper_h723_25mhz.bin
          cp -v .config         ../artifacts/.config_25mhz

          # ---- Variant B: Internal 8 MHz ----
          # Switch clock line to INTERNAL (remove 25MHz if present)
          if grep -q '^CONFIG_CLOCK_REF_25MHZ=y' .config; then
            sed -i 's/^CONFIG_CLOCK_REF_25MHZ=y/# CONFIG_CLOCK_REF_25MHZ is not set/' .config
          fi
          if ! grep -q '^CONFIG_CLOCK_REF_INTERNAL=y' .config; then
            printf '\nCONFIG_CLOCK_REF_INTERNAL=y\n' >> .config
          fi

          make clean
          make -j1
          cp -v out/klipper.bin ../artifacts/klipper_h723_internal.bin
          cp -v .config         ../artifacts/.config_internal

      # Upload both bins + configs
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-dual
          path: artifacts/*
