name: Build Klipper for AFC-Lite (STM32H723)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout config repo (this repo)
        uses: actions/checkout@v4
        with:
          path: myrepo

      - name: Checkout Klipper sources
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          # You can pin to a release if you prefer:
          # ref: v0.12.0

      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      - name: Patch Makefile to force board link, then build (single-thread)
        run: |
          set -euxo pipefail
          cd klipper
          cp ../myrepo/.config .config

          # 1) Patch the create-board-link rule so it never points to '.'
          # Original line is like:
          #   ln -snf $(if $(wildcard out/board-link),$(BOARD_DIRECTORY),.) out/board
          # Replace it to always use $(BOARD_DIRECTORY)
          sed -i -E 's|ln -snf .*\$\(BOARD_DIRECTORY\).*|ln -snf $(BOARD_DIRECTORY) out/board|' Makefile
          sed -i -E 's|ln -snf .* out/board|ln -snf $(BOARD_DIRECTORY) out/board|' Makefile

          # 2) Clean and build with an explicit BOARD_DIRECTORY
          rm -rf out
          mkdir -p out/board-generic
          # Touch the marker (not strictly needed after the patch, but harmless)
          : > out/board-link

          make BOARD_DIRECTORY=out/board-generic clean
          make -j1 BOARD_DIRECTORY=out/board-generic

          # Show what got created (for debugging if needed)
          ls -l out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: |
            klipper/out/klipper.bin
            klipper/.config
