name: klipper-afc-lite-h723-usb-build
on: { workflow_dispatch: {} }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { repository: Klipper3d/klipper, path: klipper, fetch-depth: 1 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: build
        working-directory: klipper
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3
          printf "%s\n" \
            "CONFIG_LOW_LEVEL_OPTIONS=y" \
            "CONFIG_MACH_STM32=y" \
            "CONFIG_STM32H7=y" \
            'CONFIG_MCU="stm32h723"' \
            "CONFIG_CLOCK_REF_25MHZ=y" \
            "CONFIG_FLASH_BOOTLOADER=y" \
            "CONFIG_FLASH_BOOTLOADER_0K=y" \
            "CONFIG_USB_SERIAL=y" > .config
          make olddefconfig
          make clean
          make -j1 V=1
          mkdir -p ../artifacts
          cp -v out/klipper.bin ../artifacts/klipper_h723_usb_25mhz_noboot.bin
          cp -v .config ../artifacts/.config_used

      - uses: actions/upload-artifact@v4
        with: { name: klipper-afc-lite-h723-usb, path: klipper/artifacts/* }
