name: Build Klipper for AFC-Lite (STM32H723)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout config repo (this repo)
        uses: actions/checkout@v4
        with:
          path: myrepo

      - name: Checkout Klipper sources
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          # Optional pin:
          # ref: v0.12.0

      - name: Install ARM toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3 libncurses-dev

      - name: Build firmware (isolate paths, expose headers, override link rule)
        run: |
          set -euxo pipefail
          cd klipper
          cp ../myrepo/.config .config

          # Clean slate
          rm -rf out
          mkdir -p out/board-generic

          # Expose sources/headers via board dir
          ln -sfn ../src            out/board-generic/src
          ln -sfn ../include        out/board-generic/include
          ln -sfn ../include/board  out/board-generic/board   # <-- provides board/io.h

          # Force out/board -> out/board-generic (override: last rule wins)
          {
            echo '';
            echo 'create-board-link:';
            echo '	@mkdir -p $(BOARD_DIRECTORY)';
            echo '	ln -snf $(BOARD_DIRECTORY) out/board';
          } >> Makefile

          # Debug visibility
          tail -n 12 Makefile
          ls -l out
          ls -l out/board-generic

          # Build single-threaded with forced board dir
          make BOARD_DIRECTORY=out/board-generic clean
          make -j1 BOARD_DIRECTORY=out/board-generic

          # Show final link target
          ls -l out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: |
            klipper/out/klipper.bin
            klipper/.config
