name: klipper-afc-lite-h723-usb-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Klipper
        uses: actions/checkout@v4
        with:
          repository: Klipper3d/klipper
          path: klipper
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi make python3

      - name: Build (STM32H723 + USB + 25MHz, no bootloader)
        working-directory: klipper
        run: |
          set -euxo pipefail

          # Always start from a clean tree, but do NOT use 'distclean' (it deletes .config)
          make clean || true

          # Write the correct config and lock it in
          cat > .config <<'EOF'
CONFIG_LOW_LEVEL_OPTIONS=y
CONFIG_MACH_STM32=y
CONFIG_STM32H7=y
CONFIG_MCU="stm32h723"
CONFIG_CLOCK_REF_25MHZ=y
CONFIG_FLASH_BOOTLOADER=y
CONFIG_FLASH_BOOTLOADER_0K=y
CONFIG_USB_SERIAL=y
# CONFIG_CANBUS is not set
EOF

          # Resolve defaults using ARM path
          make ARCH=arm olddefconfig

          # Build (V=1 prints the actual compiler; should be arm-none-eabi-gcc)
          make ARCH=arm -j1 V=1

          # Collect artifacts (inside klipper/)
          mkdir -p artifacts
          cp -v out/klipper.bin artifacts/klipper_h723_usb_25mhz_noboot.bin
          cp -v .config       artifacts/.config_used

          # Quick sanity checks in log
          echo "=== Expect to find arm-none-eabi-gcc here ==="
          grep -Rsn "arm-none-eabi-gcc" out || true
          echo "=== Autoconf hints (STM32/H7/H723/USB) ==="
          grep -E "STM32|H7|H723|USB" -n out/autoconf.h || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: klipper-afc-lite-h723-usb
          path: klipper/artifacts/*
